name: Build and Deploy CV

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup TinyTeX
      uses: r-lib/actions/setup-tinytex@v2
    
    - name: Install packages
      run: tlmgr install sourcesanspro sourcecodepro fontspec xetex
    
    - name: Build CVs in parallel
      run: |
        xelatex -interaction=nonstopmode cv.tex &
        xelatex -interaction=nonstopmode cv-short.tex &
        wait
        # Second pass for references  
        xelatex -interaction=nonstopmode cv.tex &
        xelatex -interaction=nonstopmode cv-short.tex &
        wait
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      id: deployment
      uses: actions/deploy-pages@v4