name: Build and Deploy CV

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build CV Full
      uses: xu-cheng/latex-action@v3
      with:
        root_file: cv.tex
        compiler: xelatex
        args: -interaction=nonstopmode
    
    - name: Build CV Short  
      uses: xu-cheng/latex-action@v3
      with:
        root_file: cv-short.tex
        compiler: xelatex
        args: -interaction=nonstopmode
    
    - name: Upload PDFs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cv-pdfs
        path: |
          cv.pdf
          cv-short.pdf
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        destination_dir: .
        keep_files: false
        include_files: |
          cv.pdf
          cv-short.pdf
          README.md